# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: faf885ee8eeedd1cdbc15b92c92e40eb8bd95be97c3cdab85bc43ab046faf8a8e18832120e88d963af1d4cad8cc8fed7e6a6532cb4a7f03d8b9f8e8e04d1a20c

test:
  secret_key_base: 9bf2eec24a195a541684866863588e0bf6b0c497ae0eebee2ea7d0af3468d1a667799855c125295b5fd2c367553a1109dea46878ff89d1dca72ec9b31f41162f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
